import type { CSSProperties } from "react";

export const s = {
  wrap: { maxWidth: 900 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 14, marginBottom: 8 } satisfies CSSProperties,
  h2: { margin: 0, fontSize: 16 } satisfies CSSProperties,
  hint: { color: "var(--text-muted)", fontSize: 12, margin: "0 0 18px" } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 7 } satisfies CSSProperties,
  row: (current: boolean) =>
    ({
      display: "flex",
      alignItems: "center",
      gap: 11,
      minHeight: 48,
      padding: "10px 14px",
      border: `1px solid ${current ? "var(--border-strong)" : "var(--border)"}`,
      borderRadius: 7,
      background: current ? "var(--bg-elevated)" : "var(--bg-surface)",
    }) satisfies CSSProperties,
  versionNumber: { fontWeight: 650, fontSize: 13, minWidth: 32 } satisfies CSSProperties,
  meta: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  metaMain: { fontSize: 13 } satisfies CSSProperties,
  metaSub: { color: "var(--text-muted)", fontSize: 11 } satisfies CSSProperties,
  actions: { display: "flex", gap: 6 } satisfies CSSProperties,
  compareGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 } satisfies CSSProperties,
  compareLabel: { fontSize: 12, fontWeight: 600, color: "var(--text-muted)", marginBottom: 6 } satisfies CSSProperties,
  comparePre: {
    margin: 0,
    padding: 12,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    fontSize: 12,
    lineHeight: 1.6,
    overflow: "auto",
    maxHeight: 480,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  } satisfies CSSProperties,
  metaSection: { marginBottom: 16 } satisfies CSSProperties,
  metaRow: { display: "flex", gap: 8, fontSize: 12, marginBottom: 4 } satisfies CSSProperties,
  metaKey: { color: "var(--text-muted)", minWidth: 90 } satisfies CSSProperties,
  metaVal: { color: "var(--text-primary)" } satisfies CSSProperties,
  modalFooter: { display: "flex", justifyContent: "flex-end" } satisfies CSSProperties,
} as const;
