import type React from "react";

export const s = {
  layout: { display: "flex", height: "calc(100vh - 52px)", minHeight: 0 } satisfies React.CSSProperties,
  sidebar: { width: 430, flexShrink: 0, borderRight: "1px solid var(--border)", display: "flex", flexDirection: "column", minHeight: 0, background: "var(--bg-surface)" } satisfies React.CSSProperties,
  sidebarHeader: { padding: "18px 18px 14px" } satisfies React.CSSProperties,
  sidebarTitleRow: { display: "flex", alignItems: "center", gap: 12, marginBottom: 16 } satisfies React.CSSProperties,
  h1: { flex: 1, margin: 0, fontSize: 18, fontWeight: 700 } satisfies React.CSSProperties,
  searchWrap: { position: "relative" } satisfies React.CSSProperties,
  searchIcon: { position: "absolute", left: 12, top: 11, color: "var(--text-muted)" } satisfies React.CSSProperties,
  search: { width: "100%", padding: "10px 12px 10px 34px", borderRadius: 7, border: "1px solid var(--border)", background: "var(--bg-primary)", color: "var(--text-primary)", outline: "none" } satisfies React.CSSProperties,
  skillList: { flex: 1, overflow: "auto", display: "flex", flexDirection: "column", gap: 10, padding: "0 12px 16px" } satisfies React.CSSProperties,
  skillCard: (active: boolean, enabled: boolean) => ({ opacity: enabled ? 1 : 0.58, minHeight: 132, borderColor: active ? "var(--border-strong)" : "var(--border)", boxShadow: active ? "inset 3px 0 0 var(--accent)" : undefined } satisfies React.CSSProperties),
  cardHead: { display: "flex", alignItems: "center", gap: 10 } satisfies React.CSSProperties,
  iconBox: { width: 30, height: 30, display: "grid", placeItems: "center", borderRadius: 7, color: "var(--accent)", background: "var(--accent-bg)" } satisfies React.CSSProperties,
  name: { flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontSize: 14, fontWeight: 700 } satisfies React.CSSProperties,
  description: { color: "var(--text-secondary)", fontSize: 13, lineHeight: 1.45, margin: "12px 0", display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical", overflow: "hidden" } satisfies React.CSSProperties,
  meta: { display: "flex", alignItems: "center", gap: 8 } satisfies React.CSSProperties,
  source: { color: "var(--text-muted)", fontSize: 12, textTransform: "capitalize" } satisfies React.CSSProperties,
  version: { marginLeft: "auto", color: "var(--text-muted)", fontSize: 12 } satisfies React.CSSProperties,
  editorOuter: { flex: 1, minWidth: 0, minHeight: 0, display: "flex", flexDirection: "column" } satisfies React.CSSProperties,
  editorHeader: { display: "flex", alignItems: "center", gap: 10, minHeight: 66, padding: "10px 28px" } satisfies React.CSSProperties,
  editorIcon: { width: 32, height: 32, display: "grid", placeItems: "center", borderRadius: 7, color: "var(--accent)", background: "var(--accent-bg)" } satisfies React.CSSProperties,
  editorTitle: { margin: 0, fontSize: 18, fontWeight: 700 } satisfies React.CSSProperties,
  editorBody: { flex: 1, minHeight: 0, overflow: "auto" } satisfies React.CSSProperties,
  emptyEditor: { flex: 1, display: "grid", placeItems: "center" } satisfies React.CSSProperties,
  panel: { maxWidth: 1120, padding: "28px 34px 48px" } satisfies React.CSSProperties,
  sectionTitleRow: { display: "flex", alignItems: "center", gap: 10, marginBottom: 22 } satisfies React.CSSProperties,
  sectionTitle: { margin: 0, fontSize: 18, fontWeight: 700 } satisfies React.CSSProperties,
  sectionHint: { margin: "8px 0 22px", color: "var(--text-secondary)", fontSize: 13, lineHeight: 1.5 } satisfies React.CSSProperties,
  versionChip: { padding: "3px 9px", borderRadius: 5, color: "var(--text-muted)", background: "var(--bg-hover)", fontSize: 12 } satisfies React.CSSProperties,
  enabledLabel: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 9, color: "var(--text-secondary)", fontSize: 13 } satisfies React.CSSProperties,
  editorShell: { border: "1px solid var(--border-strong)", borderRadius: 8, overflow: "hidden", background: "var(--bg-primary)" } satisfies React.CSSProperties,
  editorBar: { display: "flex", alignItems: "center", gap: 9, minHeight: 42, padding: "0 12px", borderBottom: "1px solid var(--border)", color: "var(--text-secondary)", fontSize: 12 } satisfies React.CSSProperties,
  unsaved: { padding: "2px 7px", borderRadius: 4, background: "var(--warn-bg)", color: "var(--warn)" } satisfies React.CSSProperties,
  tokenEstimate: { marginLeft: "auto", color: "var(--text-muted)" } satisfies React.CSSProperties,
  actions: { display: "flex", justifyContent: "flex-end", gap: 8 } satisfies React.CSSProperties,
  markdown: { marginTop: 20, padding: 28, border: "1px solid var(--border)", borderRadius: 9, background: "var(--bg-elevated)", fontSize: 15 } satisfies React.CSSProperties,
  versionList: { display: "flex", flexDirection: "column", gap: 10 } satisfies React.CSSProperties,
  versionRow: (current: boolean) => ({ minHeight: 88, display: "flex", alignItems: "center", gap: 16, padding: "14px 18px", border: `1px solid ${current ? "var(--border-strong)" : "var(--border)"}`, borderRadius: 8, background: "var(--bg-elevated)" } satisfies React.CSSProperties),
  versionNumber: { width: 42, color: "var(--accent)", fontWeight: 700 } satisfies React.CSSProperties,
  versionText: { flex: 1, display: "flex", flexDirection: "column", gap: 5, fontSize: 14 } satisfies React.CSSProperties,
  versionActions: { display: "flex", gap: 8 } satisfies React.CSSProperties,
  compareGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 1, background: "var(--border)", minHeight: 520 } satisfies React.CSSProperties,
  compareLabel: { padding: "10px 14px", background: "var(--bg-surface)", fontSize: 12, fontWeight: 700 } satisfies React.CSSProperties,
  comparePre: { margin: 0, minHeight: 480, maxHeight: "65vh", overflow: "auto", padding: 16, background: "var(--bg-primary)", color: "var(--text-secondary)", fontSize: 12, lineHeight: 1.55, whiteSpace: "pre-wrap" } satisfies React.CSSProperties,
  statsGrid: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 12 } satisfies React.CSSProperties,
  attributionNote: { margin: "14px 0 22px", color: "var(--text-muted)", fontSize: 12, lineHeight: 1.5 } satisfies React.CSSProperties,
  statsDetails: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 } satisfies React.CSSProperties,
  statsCard: { minHeight: 260, padding: 18, border: "1px solid var(--border)", borderRadius: 9, background: "var(--bg-elevated)" } satisfies React.CSSProperties,
  statsCardTitle: { display: "flex", alignItems: "center", gap: 8, marginBottom: 16, color: "var(--text-muted)", fontSize: 12, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.04em" } satisfies React.CSSProperties,
  agentRows: { display: "flex", flexDirection: "column", gap: 8 } satisfies React.CSSProperties,
  agentRow: { display: "flex", alignItems: "center", gap: 10, padding: "11px 12px", border: "1px solid var(--border)", borderRadius: 7, color: "var(--text-primary)", textDecoration: "none", background: "var(--bg-surface)" } satisfies React.CSSProperties,
  agentIcon: { width: 27, height: 27, display: "grid", placeItems: "center", borderRadius: 6, color: "var(--accent)", background: "var(--accent-bg)" } satisfies React.CSSProperties,
  openLabel: { marginLeft: "auto", color: "var(--text-muted)", fontSize: 12 } satisfies React.CSSProperties,
  donutWrap: { minHeight: 170, display: "flex", alignItems: "center", justifyContent: "center", gap: 28 } satisfies React.CSSProperties,
  cssDonut: { width: 150, height: 150, borderRadius: "50%", display: "grid", placeItems: "center", flexShrink: 0 } satisfies React.CSSProperties,
  cssDonutHole: { width: 100, height: 100, borderRadius: "50%", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", background: "var(--bg-elevated)", fontSize: 20 } satisfies React.CSSProperties,
  categoryLegend: { minWidth: 150, display: "flex", flexDirection: "column", gap: 9 } satisfies React.CSSProperties,
  categoryRow: { display: "grid", gridTemplateColumns: "10px 1fr auto", alignItems: "center", gap: 8, color: "var(--text-secondary)", fontSize: 12 } satisfies React.CSSProperties,
  categoryDot: { width: 9, height: 9, borderRadius: 2 } satisfies React.CSSProperties,
  decisionCounts: { display: "flex", justifyContent: "center", gap: 24, marginTop: 8, color: "var(--text-secondary)", fontSize: 12 } satisfies React.CSSProperties,
  drawerActions: { display: "flex", gap: 8, justifyContent: "flex-end" } satisfies React.CSSProperties,
  previewMeta: { display: "flex", gap: 8, alignItems: "center", marginBottom: 18 } satisfies React.CSSProperties,
  form: { padding: 24 } satisfies React.CSSProperties,
  trust: { padding: 14, border: "1px solid var(--warn)", borderRadius: 8, background: "var(--warn-bg)", color: "var(--text-secondary)", fontSize: 13, lineHeight: 1.5, marginBottom: 18 } satisfies React.CSSProperties,
  file: { width: "100%", padding: 14, border: "1px dashed var(--border-strong)", borderRadius: 8, color: "var(--text-secondary)" } satisfies React.CSSProperties,
  ignored: { color: "var(--text-muted)", fontSize: 12, lineHeight: 1.5, marginTop: 12 } satisfies React.CSSProperties,
};
